bootcamp/tpo/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib import auth
from django.conf import settings
from django.conf.urls.static import static
# from bootcamp.core import views as core_views


app_name = 'tpo'
urlpatterns = [
    url(r'^$', views.Home, name='Home'),
    # url(r'^', include('core.urls',namespace='student')),
    # url(r'^student', core_views.home, name='home'),
    url(r'^leavePage$', views.Leave_Page, name='Leave_Page'),
    url(r'^contactUs$', views.Contact_Us, name='Contact_Us'),
    url(r'^calender$', views.Calender, name='Calender'),
    url(r'^varanasi$', views.Varanasi, name='Varanasi'),
    url(r'^why$', views.Why, name='Why'),
    url(r'^Procedure&Policy', views.Procedure_And_Policy, name='Procedure_And_Policy'),
    url(r'^register$', views.Register, name='Register'),
    # url(r'^login$', views.Login, name='Login'),
    # url(r'^logout$', views.Logout, name='Logout'),
    url(r'^Policypdf$',views.Policy_pdf, name='Policy_pdf'),
    url(r'^zip$',views.Zip, name='Zip'),
    url(r'^feedback$', views.Feedback, name='Feedback'),
    url(r'^companyResponseSheet$', views.CompanyResponseSheet, name='CompanyResponseSheet'),
    #url(r'^startchat$', views.start_chat, name='start_chat'),
    #url(r'^chat$', views.chat, name='chat'),
    url(r'^prevrec$', views.Prevrec, name='prevrec'),
    url(r'^disciplines$', views.Disciplines, name='disciplines'),
    url(r'^overview$', views.Overview, name='overview'),
    url(r'^Beyond$', views.Beyond, name='Beyond'),
    url(r'^tpomessage$', views.Tpomessage, name='Tpomessage'),
    url(r'^facilities$', views.Facilities, name='Facilities'),
    url(r'^directormsg$', views.Directormsg, name='directormsg'),
    url(r'^tpomsg$', views.Tpomsg, name='tpomsg'),
   

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin

from tpo import urls
from bootcamp.activities import views as activities_views
from bootcamp.authentication import views as bootcamp_auth_views,views
from bootcamp.core import views as core_views
from bootcamp.search import views as search_views
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tpo.urls')),
    # url(r'^core/', include('core.urls',namespace='core')),
    url(r'^student', core_views.home, name='home'),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    # url(r'^', core_views.home, name='home'),.    
    # url(r"^notifications/", include("pinax.notifications.urls", namespace="pinax_notifications")),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'template_name': 'tpo/home.html'}, name='logout'),
    url(r'^signup/$', bootcamp_auth_views.signup, name='signup'),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('bootcamp.feeds.urls')),
    url(r'^questions/', include('bootcamp.questions.urls')),
    url(r'^articles/', include('bootcamp.articles.urls')),
    url(r'^messages/', include('bootcamp.messenger.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    # For autocomplete suggestions
    url(r'^autocomplete/$',
        search_views.get_autocomplete_suggestions, name='autocomplete'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^$', TemplateView.as_view(template_name='index.html')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

bootcamp/tpo/forms.py
from django.forms import *
from tpo.models import *
from django.contrib.auth.models import User


class LeaveForm(ModelForm):
    class Meta:
        model = LeavePage
        fields = '__all__'


class UserForm(ModelForm):
    password = CharField(widget=PasswordInput())

    class Meta:
        model = User
        #fields = '__all__'
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


class LoginForm(Form):
    username = CharField(max_length=100)
    password = CharField(widget=PasswordInput())


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = CompanyProfile
        fields = '__all__'


class StartChat(Form):
    Name = forms.CharField(max_length=100)
    Email = forms.CharField(max_length=100)


'''class CmpnyForm(ModelForm):

    class Meta:
        model = CmpnyProfile
        fields = '__all__'
        widget = {'Industry_Sector': forms.CheckboxSelectMultiple}'''

bootcamp/tpo/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import RequestContext
from django.conf import settings
from .forms import *
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
#from django.core.context_processors import csrf
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import FileResponse
from django.core.mail import send_mail, mail_admins
from django.contrib import messages
from django.core.files.storage import FileSystemStorage





def Leave_Page(request):
    form = LeaveForm()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LeaveForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in request.POST.get as required
            # ...
            # redirect to a new URL
            leave_form = form.save()
            Name = leave_form.Name
            Email = leave_form.Email
            Phone = leave_form.Phone
            Subject = leave_form.Subject
            Message = leave_form.Message
            body = "\nCompany Name - " + str(Name) + "\nMessage - " + str(Message)
            send_mail(subject=Subject, message=body, fail_silently=False, from_email="mansi.deolalikar@gmail.com",
                      recipient_list=['mlikhar45@gmail.com'])
            messages.add_message(request, messages.INFO, 'Feedback Submitted')
            print ("done")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = LeaveForm()

    return render(request, 'tpo/leavePage.html', {'form': form})


def Feedback(request):
    form = FeedbackForm()
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = FeedbackForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in request.POST.get as required
            # ...
            # redirect to a new URL
            feedback_form = form.save()


    # if a GET (or any other method) we'll create a blank form
    else:
        form = FeedbackForm()

    return render(request, 'tpo/feedback.html', {'form': form})


def Contact_Us(request):
    return render(request, 'tpo/ContactUs.html')


def Calender(request):
    return render(request, 'tpo/Calender.html')


def Home(request):
    return render(request, 'tpo/home.html')


def Varanasi(request):
    return render(request, 'tpo/varanasi.html')


def Why(request):
    return render(request, 'tpo/why.html')


def Procedure_And_Policy(request):
    return render(request, 'tpo/Procedure&Policy.html')


def Disciplines(request):
    return render(request, 'tpo/disciplines.html')


def Overview(request):
    return render(request, 'tpo/overview.html')


def Beyond(request):
    return render(request, 'tpo/Beyond.html')


def Tpomessage(request):
    return render(request, 'tpo/tpomessage.html')

def Facilities(request):
    return render(request, 'tpo/facilities.html')

def Directormsg(request):
    return render(request, 'tpo/Directormsg.html')

def Tpomsg(request):
    return render(request, 'tpo/tpomsg.html')




def Prevrec(request):
    return render(request, 'tpo/prevrec.html')


@csrf_protect
def Register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
               profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print (user_form.errors)#, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
       #s1 profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'tpo/register.html',
            {'user_form': user_form, 'registered': registered})


def Login(request):
    if request.user.id:
        logout(request)
        return render(request, 'tpo/home.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'tpo/home.html')
        return HttpResponse('User NOt found')

    form = LoginForm()
    return render(request, 'tpo/login.html',{'user':'dsf','form':form})


# def Logout(request):
#     logout(request)
#     render_to_response(request, 'tpo/home.html')


def Policy_pdf(request):
    return FileResponse(open("tpo/static/Downloads/Placement_Policy_2016_17.pdf", 'rb'), content_type='application/pdf')


def Zip(request):
    return FileResponse(open("tpo/static/Downloads/IIT(BHU)_JNF_INF.zip", 'rb'), content_type='application/zip')





def CompanyResponseSheet(request):
    context = {}
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # check whether it's valid:
        if True:
            Name_Of_the_Company = request.POST.get('Name_Of_the_Company')


            #f.Name_Of_the_Company = Name_Of_the_Company
            Address = request.POST.get('Address')
            #f.Address = Address
            Type = request.POST.get('Type')
            #f.Type = Type
            Indstry_sctr_Core = request.POST.get('Indstry_sctr_Core')
            print (Indstry_sctr_Core)
            #f.Indstry_sctr_Core = Indstry_sctr_Core
            Indstry_sctr_consulting = request.POST.get('Indstry_sctr_consulting')
            #f.Indstry_sctr_consulting = Indstry_sctr_consulting
            Indstry_sctr_IT = request.POST.get('Indstry_sctr_IT')
            #f.some_field = Indstry_sctr_IT
            Indstry_sctr_Finanace = request.POST.get('Indstry_sctr_Finanace')
            #f.Indstry_sctr_Finanace = Indstry_sctr_Finanace
            Indstry_sctr_Govrnt = request.POST.get('Indstry_sctr_Govrnt')
            #f.Indstry_sctr_Govrnt = Indstry_sctr_Govrnt
            Indstry_sctr_Other = request.POST.get('Indstry_sctr_Other')
            #f.Indstry_sctr_Other = Indstry_sctr_Other
            req_functional_areas_Red = request.POST.get('req_functional_areas_Red')
            #f.req_functional_areas_Red = req_functional_areas_Red
            req_functional_areas_Maintenance = request.POST.get('req_functional_areas_Maintenance')
            #f.req_functional_areas_Maintenance = req_functional_areas_Maintenance
            req_functional_areas_Design = request.POST.get('req_functional_areas_Design')
            #f.req_functional_areas_Design = req_functional_areas_Design
            req_functional_areas_Production = request.POST.get('req_functional_areas_Production')
            #f.req_functional_areas_Production = req_functional_areas_Production
            req_functional_areas_RD = request.POST.get('req_functional_areas_RD')
            #f.req_functional_areas_RD = req_functional_areas_RD
            req_functional_areas_Others = request.POST.get('req_functional_areas_Others')
            #f.req_functional_areas_Others = req_functional_areas_Others
            req_functional_areas_Finance = request.POST.get('req_functional_areas_Finance')
            #f.req_functional_areas_Finance = req_functional_areas_Finance
            VsnandInterest = request.POST.get('VsnandInterest')
            #f.VsnandInterest = VsnandInterest
            PrsnName = request.POST.get('PrsnName')
            #f.PrsnName = PrsnName
            PrsnDesignation = request.POST.get('PrsnDesignation')
            #f.PrsnDesignation = PrsnDesignation
            PrsnPhone = request.POST.get('PrsnPhone')
            #f.PrsnPhone = PrsnPhone
            PrsnEmail = request.POST.get('PrsnEmail')
            #f.PrsnEmail = PrsnEmail
            CGPA = request.POST.get('CGPA')
            #f.CGPA = CGPA
            XII_perc = request.POST.get('XII_perc ')
            #f.XII_perc  = XII_perc

bootcamp/tpo/templates/tpo/base.html
<!DOCTYPE html>

{% load static %}
  <html>
    <head>
		<!--Import Google Icon Font-->
		<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<!--Import materialize.css-->
		<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}" media="screen,projection"/>
		<!--Let browser know website is optimized for mobile-->
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">
		<link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    </head>

    <body>
		<div>
			<ul id="dropdown1" class="dropdown-content">
			  			  <li><a href="{% url 'tpo:Procedure_And_Policy' %}" class="menu">Procedure and Policy</a></li>
			  <li class="divider"></li>
				<li><a href="{% url 'tpo:CompanyResponseSheet' %}" class="menu">Company Response Form</a></li>
			  <li class="divider"></li>
			  <li><a href="{% url 'tpo:prevrec' %}" class="menu">Past Recruters</a></li>
			  <li class="divider"></li>
			  <li><a href="{% url 'tpo:Calender' %}" class="menu">Placement Calender</a></li>
			  <li class="divider"></li>
			  <li><a href="{% url 'tpo:Zip' %}" class="menu" target="_blank">Job Notification form</a></li>
			  <li class="divider"></li>
			</ul>
			<ul id="dropdown2" class="dropdown-content">
			  <li><a href="{% url 'tpo:Contact_Us' %}" class="menu">Office</a></li>
			  <li class="divider"></li>
			  <li><a href="{% url 'tpo:Leave_Page' %}" class="menu">Leave Message</a></li>
			  <li class="divider"></li>
			  <li><a href="{% url 'tpo:Feedback' %}" class="menu">Feedback</a></li>
				<li class="divider"></li>
			  
			</ul>
			<ul id="dropdown3" class="dropdown-content">
			  <li><a href="{% url 'tpo:overview' %}" class="menu">Overview</a></li>
			  <li class="divider"></li>
				<li><a href="{% url 'tpo:disciplines' %}" class="menu">Disciplines</a></li>
			  <li class="divider"></li>
			  
			</ul>
			<div class="navbar-wrapper">
			<nav style="background-image: url('../static/images/varanasi.jpg') ;height:auto" class="z-depth-4">
				<table width="100%" style="table-layout:auto">
					<tbody>
						<tr>
							<td width="37%" align="right"><div style="height:auto"><img align="right" <a href="{% url 'tpo:Feedback' %}" src="{% static 'images/iistlogo.png' %}"/> </div></td>
							<td width="38%" style="color: #000000;"><div style="height:auto">
								
								<p><font size="5">Indore Institute of Science & Technology </font>
								<br><font size="6">Training and Placement Cell</font>
								<br><font size="2">
									<a href="mailto:tpo@iitbhu.ac.in" style="color:black">tpo@iistindore.co</a> 
									
									
								</font></p>
							</div></td>
							<td width="25%"></td>
						</tr>
					</tbody>
				</table>
				<div class="row">
				<div class="container">
				<div class="col s10">
				  
				  <ul class="nav-center" id="nav-mobile" class="left hide-on-med-and-down">
					<li><a href="{% url 'tpo:Home' %}" class="menu">Home</a></li>
					<li><a href="{% url 'tpo:Why' %}" class="menu">Why recruit at IIST</a></li>
					<li><a class="dropdown-button menu" href="{% url 'tpo:Procedure_And_Policy' %}" data-activates="dropdown1"  >Companies</a></li>
					<li><a href="{% url 'tpo:overview' %}" class="dropdown-button menu" data-activates="dropdown3">Academics</a></li>
					<li><a href="{% url 'tpo:Contact_Us' %}" class="dropdown-button menu" data-activates="dropdown2" >Contact Us</a></li>
					  
				  </ul>
				</div>
			
				<a href="{% url 'home' %}" class="dropdown-button menu" >STUDENT LOGIN</a>
			
		   
				</div>
			</nav>
			</div>
		</div>
{% block content %}
		{% endblock %}
		<footer class="page-footer" style="background-color: #eeeeee" height="auto" >
          <div class="container">
            <div class="row" style="margin-bottom:0px">
              <div class="col s12">
                <center><p>&copy Indore Institute of Science & Technology,Opposite IIM-Indore,Rau</p></center>
              </div>
              <table class="layout">
					<tbody>
						<tr>
							<td width="12%"></td>
							<td align="left" style="width: 100px; text-align: right;"><img width="70%" height="80%" src="{% static 'images/logoCopy.png' %}"/></td>
							<td style="color: #000000;">
								<div class="col s6">
								  <!--<ul class="nav-center" id="nav-mobile" class="center hide-on-med-and-right">-->
									<td><a href="#!" >Home</a></td>
									<td><a href="#!" >Events</a></td>
									<td><a href="#!" >News</a></td>
									<td><a href="#!" >Academics</a></td>
									<td><a href="#!" >Administration</a></td>
									<td><a href="#!" >Library</a></td>
									<td><a href="#!" >Placements</a></td>
									<td width="15%"></td>
								  <!--</ul>-->
								</div>
							</td>
						</tr>
					</tbody>
			  </table>
			  </div>
			</footer>
		</div>
		</div>
            </div>
          </div>
        </footer>
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    </body>
  </html>

bootcamp/tpo/templates/tpo/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="/chat">chat</a>
</body>
</html>

bootcamp/tpo/templates/tpo/home.html
{% extends 'tpo/base.html' %}
{% load static %}

{% block content %}
		<div style="margin-top:2%;" class="container">
			<h3 class="fleft">Welcome to Training &amp; Placement Cell</h3>
			<!-- <div class="statemenu fright">
				<ul class="vertical">
				<li><a href="{% url 'tpo:Zip' %}" class="" target="_blank">Job Notification Form <img src="{% static 'images/response.png' %}" style="margin: -8px 0;" alt="DOWNLOAD" class="thumbhead"></a></li>
				</ul>
			</div>
			&nbsp; -->
			<!-- <div class="statemenu fright">
				<ul class="vertical">
				<li><a href="{% url 'tpo:Policy_pdf' %}" target="_blank">Placement Brochure <img src="{% static 'images/brochure.png' %}" style="margin: -8px 0;" alt="DOWNLOAD" class="thumbhead"></a></li>
				</ul>
			</div> -->
			<table class="layout">
			<tbody>
				<tr>
					<td rowspan="8" style="width: 50%; padding: 5px; border-right: 1px dashed #CCC;text-align:left">
						<p>The Training &amp; Placement Office, IIST facilitates the process of placement of students passing out from the Institute besides collaborating with leading organizations and institutes in setting up of internship and training program of students.</p>
						<br>					
						<p><img src="{% static 'images/tpo.jpg' %}" class="fleft" style="width: 60%; padding: 0 15px 0 0;"></p>
						<p>The office liaises with various industrial establishments, corporate houses etc which conduct campus interviews and select graduate and post-graduate students from all disciplines. The Training &amp; Placement Office provides the infra-structural facilities to conduct group discussions, tests and interviews besides catering to other logistics. The Office interacts with many industries in the country, of which nearly 200 companies visit the campus for holding campus interviews. The industries which approach the institute come under the purview of:						</p>
						<ul>							
						<li>Core Engineering industries</li>
						<li>IT &amp; IT enabled services</li>
						<li>Manufacturing Industries</li>
						<li>Consultancy Firms</li>
						<li>Finance Companies</li>
						<li>Management Organisations</li>
						<li>R &amp; D laboratories</li>
						</ul>
						<p>
						</p>
						<p>The placement season runs through the course of the year commencing the last week of July through to March. Pre-Placement Talks are also conducted in this regard as per mutual convenience. Job offers, dates of interviews, selection of candidates etc. are announced through the Training &amp; Placement Office.</p>
						<br>
						<p>The Placement Office is assisted by a committee comprising representatives of students from the under-graduate and post-graduate engineering streams. The committee evolves a broad policy framework every year besides a set of rules which are inviolable. Students members are closely co-opted in implementing these policy decisions.</p>
					</td>
					<!-- &nbsp; -->
					<td style="padding: 5px;text-align:left">
						<h5>Invitation Messages</h5>
						<div class="thumb80" style="background: url('{% static 'images/kittur.jpg' %}') no-repeat left center; background-size: 80px 80px;">
						<p>It gives us immense pleasure to extend to you a most cordial invitation to participate in the Campus Recruitment Programme of the Institute  ... <br>
						<a href="{% url 'tpo:tpomsg' %}" class="navigate">Message from TPO</a></p>
						</div>
					</td>
				</tr>
				<tr>
					<td style="padding: 5px; border-bottom: 1px dashed #CCC;text-align:left">
						<div class="thumb80" style="background: url('{% static 'images/director.jpg' %}') no-repeat left center; background-size: 80px 80px;">
						<p>Greetings from Indore Institute of Science and Technology ! Knowledge and continuous learning are the mainstays amongst the leading organizations today ... <br>
						<a href="{% url 'tpo:directormsg' %}" class="navigate">Message from Director</a></p>
						</div>
					</td>
				</tr>

				<tr>
				
				</tr>
				<tr>
					<!-- <td style="padding: 5px; border-bottom: 1px dashed #CCC;text-align:left">
						
					</td> -->
				</tr>
				<tr>
					<td style="padding: 5px;text-align:left">
						<h5>Placements</h5>
						<div class="thumb100" style="background: url('{% static 'images/tpo.jpg' %}') no-repeat left center; background-size: 100px 75px;">
						<p>Besides a warm welcome, we provide companies with the following aid : 1. Large classrooms &amp; halls for Pre-Placement Talks and Written Tests ... <br>
						<a href="{% url 'tpo:Facilities' %}" class="ui">Company Facilities</a></p>
						</div>
					</td>
				</tr>
				<tr style="border-bottom: 1px dashed #CCC;">
					<td style="padding: 5px;text-align:left">
						<div class="thumb100" style="background: url('{% static 'images/brochure.jpg' %}') no-repeat left center; background-size: 100px 75px;">
						<p>Our brochure provides profile of the Institute, as well as detailing the various programmes/courses offered by the departments, and details of the contact ... <br>
						<a href="{% url 'tpo:Policy_pdf' %}" target="_blank">IIST Indore
						 Placement Brochure</a></p>
						</div>
					</td>
				</tr>
				<tr>
					<td style="padding: 5px;text-align:left">
						<h5>Why Recruit @ IIST Indore
						 ?</h5>
						<div class="thumb100" style="background: url('{% static 'images/bhugate.jpg' %}') no-repeat left center; background-size: 100px 70px;">
						<p>Admission to IIST Indore
						 takes place through the Joint Entrance Examination (JEE) followed by the Indian Institutes of Technology (IITs) ... <br>
						<a href="info/why-at-iit-bhu-varanasi/" class="ui">IIST Indore
						 Advantage</a></p>
						</div>
					</td>
				</tr>
				<tr>
					<td style="padding: 5px; border-bottom: 1px dashed #CCC;text-align:left">
						<div class="thumb100" style="background: url('{% static 'images/alumni.jpg' %}') no-repeat left center; background-size: 100px 70px;">
						<p>The alumni of the institute occupy the echelons of the corporate ladder courtesy a dynamic, ever-evolving system where priority is placed ... <br>
						<a href="info/why-at-iit-bhu-varanasi/#!/view/#adv-alumni/" class="ui">IIST Indore
						 Alumni</a></p>
						</div>
					</td>
				</tr>
				<tr>
					<td style="text-align:left">
						<h5>Contact Us</h5>
						<div class="thumb80" style="background: url('{% static 'images/kittur.jpg' %}') no-repeat left center; background-size: 75px 75px;">
						<p>The Professor Incharge and office staff members may be contacted over email or telephone for information on training and placement at IIST Indore
						 ... <br>
						<a href="{% url 'tpo:Contact_Us' %}" class="ui">Office Contacts</a></p>
						</div>
					</td>
					<td style="text-align:left">
						<h5>&nbsp;</h5>
						<!-- <div class="thumb100" style="background: url('{% static 'images/indore.jpg' %}') no-repeat left center; background-size: 100px 75px;">
						<p>Indore is the cultural capital of India and the melting pot of Indian civilization. Varanasi or Benaras has a well-developed transport network and is well ... <br>
						<a href="{% url 'tpo:Varanasi' %}" class="ui">Indore</a></p>
						</div> -->
					</td>
				</tr>
				</tbody>
				<tbody>
				</tbody>
			</table>
		</div>
{% endblock %}